apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LQrDVf5c2BUSKONxdnzsQX8sVxyqvGbPKBMcCZub3ZadYs8I,iv:zLv+FBfn64P0v1dKBjUw03z452BIxitw0bNjUHGMEKM=,tag:lajnA5/NvcHgZoi+5tttyQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:lawYKQRzhvCUOpID4SO03AEU1+R4ltXvuL8nebuEV3zSW3X4c2G/XtJakUyHeXsaEJEsMxQUfM8Yzr2It+82qxpIOfDmP5CSM5Yq3ISFfF1fBTTYpk1e3XmNFgkEvLMfr83KrkrJCxlx3pj/zlAg6KXvaOEa/7lvrsBnvBmALqSrpd1K4gncml/EyfrgSPDqR+LOsB8dWLeTq5WnFwiZhrlE23QQVH/BDaxUP9m0vw==,iv:vUNCrXyf622Sl243DO8vFcpH9J86PZl2si1IsMhw0+0=,tag:NQfNmZKItSP5ytv1npAX1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tyfpnkcp0wvlkfz2j3tdhcw4aghvwp36qepdndjkmhmy9h3ygczswkxtf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweEpRY2t0UGQrK05LcVRk
            VE9YSG45NWtkd21xemErMGczZ0dWb1RtTVVjCnVZaUdwVVNTWFFoQnRtcllDTGlt
            TVdJNUt2Q1BRdTJYTDcrd0FYMVJGT00KLS0tIHh6eE03VUh5RHRkVWZRRUJqZk1N
            Vkk1cy9UOFhPcHN2WnBGZ0thVXBsVlkKx9dViXbGUnIxUpI3IrINBH1obaVBqtDc
            z6ywJjmD6OXbMm5oYooE4QJwSJWLeEo1jyZ423ehfsGLZ22/L9BSpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T06:23:32Z"
    mac: ENC[AES256_GCM,data:2VwNaVZDVp3RbiW1m8OY0wa1SVM0LWzEWvNjM/M46C//9ZC6Liug3gilEn/Mk5Or/6FPrcWcxSd3zyGiL7jmZgzrpwi2Zhz4XckiFTyv+2d36hq7k1lOBvl6kcB+phzO7vAHrC94B0jjIr5yWkpxBUcoxeZaObYI3nBMpMgvITM=,iv:NRXwtNl74pmNIG2lZZpnHQqPnaaVZG3CAjOqZKB77B8=,tag:fp+d+vuuw0393QqOR1YxIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
